# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/williamleonards/Documents/TradeMatcher

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/williamleonards/Documents/TradeMatcher

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/williamleonards/Documents/TradeMatcher/CMakeFiles /Users/williamleonards/Documents/TradeMatcher/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/williamleonards/Documents/TradeMatcher/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TradeMatcher

# Build rule for target.
TradeMatcher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TradeMatcher
.PHONY : TradeMatcher

# fast build rule for target.
TradeMatcher/fast:
	$(MAKE) -f CMakeFiles/TradeMatcher.dir/build.make CMakeFiles/TradeMatcher.dir/build
.PHONY : TradeMatcher/fast

source/Order.o: source/Order.cpp.o

.PHONY : source/Order.o

# target to build an object file
source/Order.cpp.o:
	$(MAKE) -f CMakeFiles/TradeMatcher.dir/build.make CMakeFiles/TradeMatcher.dir/source/Order.cpp.o
.PHONY : source/Order.cpp.o

source/Order.i: source/Order.cpp.i

.PHONY : source/Order.i

# target to preprocess a source file
source/Order.cpp.i:
	$(MAKE) -f CMakeFiles/TradeMatcher.dir/build.make CMakeFiles/TradeMatcher.dir/source/Order.cpp.i
.PHONY : source/Order.cpp.i

source/Order.s: source/Order.cpp.s

.PHONY : source/Order.s

# target to generate assembly for a file
source/Order.cpp.s:
	$(MAKE) -f CMakeFiles/TradeMatcher.dir/build.make CMakeFiles/TradeMatcher.dir/source/Order.cpp.s
.PHONY : source/Order.cpp.s

source/Trade.o: source/Trade.cpp.o

.PHONY : source/Trade.o

# target to build an object file
source/Trade.cpp.o:
	$(MAKE) -f CMakeFiles/TradeMatcher.dir/build.make CMakeFiles/TradeMatcher.dir/source/Trade.cpp.o
.PHONY : source/Trade.cpp.o

source/Trade.i: source/Trade.cpp.i

.PHONY : source/Trade.i

# target to preprocess a source file
source/Trade.cpp.i:
	$(MAKE) -f CMakeFiles/TradeMatcher.dir/build.make CMakeFiles/TradeMatcher.dir/source/Trade.cpp.i
.PHONY : source/Trade.cpp.i

source/Trade.s: source/Trade.cpp.s

.PHONY : source/Trade.s

# target to generate assembly for a file
source/Trade.cpp.s:
	$(MAKE) -f CMakeFiles/TradeMatcher.dir/build.make CMakeFiles/TradeMatcher.dir/source/Trade.cpp.s
.PHONY : source/Trade.cpp.s

source/TradeEngine.o: source/TradeEngine.cpp.o

.PHONY : source/TradeEngine.o

# target to build an object file
source/TradeEngine.cpp.o:
	$(MAKE) -f CMakeFiles/TradeMatcher.dir/build.make CMakeFiles/TradeMatcher.dir/source/TradeEngine.cpp.o
.PHONY : source/TradeEngine.cpp.o

source/TradeEngine.i: source/TradeEngine.cpp.i

.PHONY : source/TradeEngine.i

# target to preprocess a source file
source/TradeEngine.cpp.i:
	$(MAKE) -f CMakeFiles/TradeMatcher.dir/build.make CMakeFiles/TradeMatcher.dir/source/TradeEngine.cpp.i
.PHONY : source/TradeEngine.cpp.i

source/TradeEngine.s: source/TradeEngine.cpp.s

.PHONY : source/TradeEngine.s

# target to generate assembly for a file
source/TradeEngine.cpp.s:
	$(MAKE) -f CMakeFiles/TradeMatcher.dir/build.make CMakeFiles/TradeMatcher.dir/source/TradeEngine.cpp.s
.PHONY : source/TradeEngine.cpp.s

source/User.o: source/User.cpp.o

.PHONY : source/User.o

# target to build an object file
source/User.cpp.o:
	$(MAKE) -f CMakeFiles/TradeMatcher.dir/build.make CMakeFiles/TradeMatcher.dir/source/User.cpp.o
.PHONY : source/User.cpp.o

source/User.i: source/User.cpp.i

.PHONY : source/User.i

# target to preprocess a source file
source/User.cpp.i:
	$(MAKE) -f CMakeFiles/TradeMatcher.dir/build.make CMakeFiles/TradeMatcher.dir/source/User.cpp.i
.PHONY : source/User.cpp.i

source/User.s: source/User.cpp.s

.PHONY : source/User.s

# target to generate assembly for a file
source/User.cpp.s:
	$(MAKE) -f CMakeFiles/TradeMatcher.dir/build.make CMakeFiles/TradeMatcher.dir/source/User.cpp.s
.PHONY : source/User.cpp.s

source/main.o: source/main.cpp.o

.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) -f CMakeFiles/TradeMatcher.dir/build.make CMakeFiles/TradeMatcher.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i

.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) -f CMakeFiles/TradeMatcher.dir/build.make CMakeFiles/TradeMatcher.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s

.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) -f CMakeFiles/TradeMatcher.dir/build.make CMakeFiles/TradeMatcher.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

test/test.o: test/test.cpp.o

.PHONY : test/test.o

# target to build an object file
test/test.cpp.o:
	$(MAKE) -f CMakeFiles/TradeMatcher.dir/build.make CMakeFiles/TradeMatcher.dir/test/test.cpp.o
.PHONY : test/test.cpp.o

test/test.i: test/test.cpp.i

.PHONY : test/test.i

# target to preprocess a source file
test/test.cpp.i:
	$(MAKE) -f CMakeFiles/TradeMatcher.dir/build.make CMakeFiles/TradeMatcher.dir/test/test.cpp.i
.PHONY : test/test.cpp.i

test/test.s: test/test.cpp.s

.PHONY : test/test.s

# target to generate assembly for a file
test/test.cpp.s:
	$(MAKE) -f CMakeFiles/TradeMatcher.dir/build.make CMakeFiles/TradeMatcher.dir/test/test.cpp.s
.PHONY : test/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TradeMatcher"
	@echo "... source/Order.o"
	@echo "... source/Order.i"
	@echo "... source/Order.s"
	@echo "... source/Trade.o"
	@echo "... source/Trade.i"
	@echo "... source/Trade.s"
	@echo "... source/TradeEngine.o"
	@echo "... source/TradeEngine.i"
	@echo "... source/TradeEngine.s"
	@echo "... source/User.o"
	@echo "... source/User.i"
	@echo "... source/User.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

